# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

     

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


## Using NumPy

Once you've installed NumPy you can import it as a library:

In [34]:
import numpy as np

np.random.seed(0)

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [6]:
my_array = [1, 2, 3]

my_array

[1, 2, 3]

In [7]:
np.array(my_array)

array([1, 2, 3])

In [9]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [10]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [14]:
np.arange(10, 20+1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
np.arange(0, 21+1, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21])

### zeros and ones

Generate arrays of zeros or ones

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [28]:
np.ones((4,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [56]:
np.random.rand(20)

array([0.75837865, 0.32001715, 0.38346389, 0.58831711, 0.83104846,
       0.62898184, 0.87265066, 0.27354203, 0.79804683, 0.18563594,
       0.95279166, 0.68748828, 0.21550768, 0.94737059, 0.73085581,
       0.25394164, 0.21331198, 0.51820071, 0.02566272, 0.20747008])

In [55]:
np.random.rand(5,5)

array([[0.39822106, 0.20984375, 0.18619301, 0.94437239, 0.7395508 ],
       [0.49045881, 0.22741463, 0.25435648, 0.05802916, 0.43441663],
       [0.31179588, 0.69634349, 0.37775184, 0.17960368, 0.02467873],
       [0.06724963, 0.67939277, 0.45369684, 0.53657921, 0.89667129],
       [0.99033895, 0.21689698, 0.6630782 , 0.26332238, 0.020651  ]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [49]:
np.random.randn(3)

array([ 0.4253934 , -0.02797118,  1.47598983])

In [51]:
np.random.randn(4,4)

array([[ 0.38116374, -0.99090328,  1.01788005,  0.3415874 ],
       [-1.25088622,  0.92525075, -0.90478616,  1.84369153],
       [ 1.52550724, -1.44553558,  0.37716061, -0.07055723],
       [ 0.60415971,  0.472149  ,  0.81991729,  0.90751962]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [77]:
np.random.randint(1,100)

59

In [80]:
np.random.randint(1,100, 20)

array([24, 25,  5, 50, 88, 31, 55, 26, 21, 98, 58, 24, 28, 30, 34, 54, 52,
       87,  8, 10])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [90]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [91]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [92]:
ranarr

array([36,  4, 16, 48, 47, 10, 45, 40, 30, 27])

## Reshape
Returns an array containing the same data with a new shape.

In [93]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [94]:
ranarr

array([36,  4, 16, 48, 47, 10, 45, 40, 30, 27])

In [95]:
ranarr.max()

48

In [96]:
ranarr.min()

4

In [99]:
ranarr.argmax()

3

In [98]:
ranarr.argmin()

1

## Shape

Shape is an attribute that arrays have (not a method):

In [105]:
# Vector
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [106]:
# Vector
arr.shape

(25,)

In [108]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [110]:
arr.reshape(1,25).shape

(1, 25)

In [111]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [112]:
arr.reshape(25, 1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [119]:

np.array([0,23]).dtype

dtype('int64')

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [143]:
#Creating sample array
arr = np.arange(0,11)

In [121]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [124]:
#Get a value at an index
arr[-6]

5

In [129]:
#Get values in a range
arr[2:9:2]

array([2, 4, 6, 8])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [147]:
#Setting a value with index range (Broadcasting)
arr[3:6] = 0

#Show
arr

array([ 0,  1,  2,  0,  0,  0,  6,  7,  8,  9, 10])

In [148]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [149]:
#Important notes on Slices
slice_Arr = arr[2:8]

#Show slice
slice_Arr

array([2, 3, 4, 5, 6, 7])

In [150]:
#Change Slice
slice_Arr[:] = 99

#Show Slice again
slice_Arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [151]:
arr

array([ 0,  1, 99, 99, 99, 99, 99, 99,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [152]:
#To get a copy, need to be explicit
slice_Arr = arr.copy()

slice_Arr

array([ 0,  1, 99, 99, 99, 99, 99, 99,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [153]:
arr_2d = np.array([[ 5, 10, 15],[20, 25, 30],[35, 40, 45]])

#Show
arr_2d

r      c
    0   1   2
0 [ 5, 10, 15],
1 [20, 25, 30],
2 [35, 40, 45]


array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [170]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [159]:
#Indexing row

arr_2d[1]

array([20, 25, 30])

In [162]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][2]

30

In [165]:
# Getting individual element value
arr_2d[1,0]

20

In [166]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [171]:
#Shape bottom row
arr_2d[2]

array([35, 40, 45])

In [172]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. 

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [173]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [175]:
arr_condition1 = arr > 4

In [177]:
arr[arr_condition1]

array([ 5,  6,  7,  8,  9, 10])

In [179]:
arr_condition2 = arr % 2 == 0

In [180]:
arr[arr_condition2]

array([ 2,  4,  6,  8, 10])

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Operations

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [203]:
arr = np.arange(0,10)


In [188]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
arr = arr + arr + arr
arr

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81])

In [194]:
3 - arr

array([  3,  -6, -15, -24, -33, -42, -51, -60, -69, -78])

In [195]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [196]:
arr

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81])

In [197]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr / arr

/tmp/ipykernel_1744/1352063791.py:3: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [198]:
# Also warning, but not an error instead infinity
1 / arr

/tmp/ipykernel_1744/3632943242.py:2: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 0.11111111, 0.05555556, 0.03703704, 0.02777778,
       0.02222222, 0.01851852, 0.01587302, 0.01388889, 0.01234568])

In [202]:
arr ** 20

array([                   0, -6289078614652622815,  4981704660114997248,
       -3535985420588157519,  2299123893656354816,  6545036034076902481,
        9216948824597069824,  2404965558093863681,  1152921504606846976,
        4389419161382147137])

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [204]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [206]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [207]:
#same as arr.max()
np.max(arr)

9